name: Run lint

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
  contents: read

jobs:
    run-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
              with:
                egress-policy: audit

            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
            - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
              with:
                  node-version: 18
            - run: npm ci && npm run lint
