name: Build and push the release image

on:
    push:
        branches:
            - release

permissions:
  contents: read

jobs:
    run-pre-checks:
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
              with:
                egress-policy: audit

            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
            - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
              with:
                  node-version: 18
            - run: |
                  sudo bash -c "mkdir /captain && chown -R `whoami` /captain"
                  npm ci
                  npm run build
                  npm run lint
                  npm run formatter
                  npm run test
    build-publish-docker-hub:
        needs: run-pre-checks
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
              with:
                egress-policy: audit

            - uses: azure/docker-login@83efeb77770c98b620c73055fbb59b2847e17dc0 # v1.0.1
              with:
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
            - name: Build and Push Release to DockerHub
              shell: bash
              run: ./dev-scripts/build_and_push_release.sh
